apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: neerajbhatia/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
